# Generated by Django 6.1.1 on 2026-10-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='is_manually_edited',
            field=models.BooleanField(default=False),
        ),
    ]
